In [1]:
import pandas as pd

In [2]:
df_con = pd.read_csv("data/CONCEPT.csv", sep="\t")
df_rel = pd.read_csv("data/CONCEPT_RELATIONSHIP.csv", sep="\t")

/tmp/ipykernel_45324/2402726025.py:1: DtypeWarning: Columns (6: concept_code, 9: invalid_reason) have mixed types. Specify dtype option on import or set low_memory=False.
  df_con = pd.read_csv("data/CONCEPT.csv", sep="\t")

In [3]:
df_con.head(10)

,concept_id,concept_name,domain_id,vocabulary_id,concept_class_id,standard_concept,concept_code,valid_start_date,valid_end_date,invalid_reason
0,1146945,concept.concept_id,Metadata,CDM,Field,S,CDM1,20141111,20991231,NaN
1,1146954,concept.invalid_reason,Metadata,CDM,Field,S,CDM10,20141111,20991231,NaN
2,1147044,observation_period.observation_period_id,Metadata,CDM,Field,S,CDM100,20141111,20991231,NaN
3,756315,metadata.metadata_type_concept_id,Metadata,CDM,Field,S,CDM1000,20210925,20991231,NaN
4,756316,metadata.name,Metadata,CDM,Field,S,CDM1001,20210925,20991231,NaN
5,756317,metadata.value_as_concept_id,Metadata,CDM,Field,S,CDM1002,20210925,20991231,NaN
6,756318,metadata.value_as_number,Metadata,CDM,Field,S,CDM1003,20210925,20991231,NaN
7,756319,metadata.value_as_string,Metadata,CDM,Field,S,CDM1004,20210925,20991231,NaN
8,756320,note.note_event_field_concept_id,Metadata,CDM,Field,S,CDM1005,20210925,20991231,NaN
9,756321,note.note_event_id,Metadata,CDM,Field,S,CDM1006,20210925,20991231,NaN

In [4]:
df_rel.head(10)

,concept_id_1,concept_id_2,relationship_id,valid_start_date,valid_end_date,invalid_reason
0,41881315,41881315,Mapped from,20190221,20991231,NaN
1,41881315,41881315,Maps to,20190221,20991231,NaN
2,41881315,41881316,Subsumes,19700101,20991231,NaN
3,41881315,41881317,Subsumes,19700101,20991231,NaN
4,41881315,41881318,Subsumes,19700101,20991231,NaN
5,41881315,41881319,Subsumes,19700101,20991231,NaN
6,41881315,41881320,Subsumes,19700101,20991231,NaN
7,41881315,41881321,Subsumes,19700101,20991231,NaN
8,41881315,41881322,Subsumes,19700101,20991231,NaN
9,41881315,41881323,Subsumes,19700101,20991231,NaN

In [5]:
treg = "Carboplatin and Paclitaxel"
df_con[df_con.concept_name.str.contains(treg)]

,concept_id,concept_name,domain_id,vocabulary_id,concept_class_id,standard_concept,concept_code,valid_start_date,valid_end_date,invalid_reason
3297,35805350,Carboplatin and Paclitaxel (CP) and RT,Regimen,HemOnc,Regimen,S,17996,20190527,20991231,NaN
4330,35803572,Carboplatin and Paclitaxel (CP),Regimen,HemOnc,Regimen,S,2554,20190527,20991231,NaN
4528,1524904,"Carboplatin and Paclitaxel (CP), Bevacizumab, ...",Regimen,HemOnc,Regimen,S,26720,20220105,20991231,NaN
4664,905588,Carboplatin and Paclitaxel (CP) and Ipilimumab...,Regimen,HemOnc,Regimen,S,2822,20210224,20991231,NaN
4769,35806401,Carboplatin and Paclitaxel (CP) and Bevacizumab,Regimen,HemOnc,Regimen,S,29570,20190527,20991231,NaN
...,...,...,...,...,...,...,...,...,...,...
218978,37561600,"Carboplatin and Paclitaxel (CP), Bevacizumab-m...",Regimen,HemOnc,Regimen,S,145217,20241213,20991231,NaN
218979,37561601,"Carboplatin and Paclitaxel (CP), Bevacizumab-o...",Regimen,HemOnc,Regimen,S,145218,20241213,20991231,NaN
218980,37561602,"Carboplatin and Paclitaxel (CP), Bevacizumab-t...",Regimen,HemOnc,Regimen,S,145219,20241213,20991231,NaN
218981,37561603,"Carboplatin and Paclitaxel (CP), Bevacizumab-t...",Regimen,HemOnc,Regimen,S,145220,20241213,20991231,NaN
218982,37561604,"Carboplatin and Paclitaxel (CP), Bevacizumab, ...",Regimen,HemOnc,Regimen,S,145221,20241213,20991231,NaN

In [6]:
df_rel[(df_rel.concept_id_1 == 35803572) & (df_rel.relationship_id.str.contains("Has cytotoxic chemo"))]

,concept_id_1,concept_id_2,relationship_id,valid_start_date,valid_end_date,invalid_reason
822135,35803572,35803229,Has cytotoxic chemo,20210908,20991231,NaN
822136,35803572,35802941,Has cytotoxic chemo,20210908,20991231,NaN

In [7]:
df_con[df_con.concept_id == 35803229]

,concept_id,concept_name,domain_id,vocabulary_id,concept_class_id,standard_concept,concept_code,valid_start_date,valid_end_date,invalid_reason
5915,35803229,Paclitaxel,Drug,HemOnc,Component,NaN,379,20190527,20991231,NaN

In [8]:

df_con[df_con.concept_id == 35802941]

,concept_id,concept_name,domain_id,vocabulary_id,concept_class_id,standard_concept,concept_code,valid_start_date,valid_end_date,invalid_reason
8718,35802941,Carboplatin,Drug,HemOnc,Component,NaN,88,20190527,20991231,NaN

In [9]:
df_rel[df_rel.concept_id_1 == 35803229][df_rel.relationship_id.str.contains("Is a")]

/tmp/ipykernel_45324/3976173612.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_rel[df_rel.concept_id_1 == 35803229][df_rel.relationship_id.str.contains("Is a")]

,concept_id_1,concept_id_2,relationship_id,valid_start_date,valid_end_date,invalid_reason
1100872,35803229,35807220,Is a,20190527,20991231,NaN
1100873,35803229,35807223,Is a,20190527,20991231,NaN
1100874,35803229,35807235,Is a,20190527,20991231,NaN
1100875,35803229,35807250,Is a,20190527,20991231,NaN
1100877,35803229,35807304,Is a,20190527,20991231,NaN

In [10]:
# Concept class id Component => substance, otherwise go through brand name relationships